/**
 * Copyright (c) 2010-present Abixen Systems. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

(function () {

    'use strict';

    angular
        .module('platformFAModalSelection')
        .factory('FaSelectionModalWindowServices', FaSelectionModalWindowServices);

    FaSelectionModalWindowServices.$inject = ['ModalSelectionWindowService'];

    function FaSelectionModalWindowServices(ModalSelectionWindowService) {
        var okButtonClass = '';
        var cancelButtonClass = '';
        var windowClass = '';

        //  fa awesome data.
        var data = [
            {'id': 'fa fa-glass', 'text': 'fa fa-glass', 'selected': 'N'},
            {'id': 'fa fa-music', 'text': 'fa fa-music', 'selected': 'N'},
            {'id': 'fa fa-search', 'text': 'fa fa-search', 'selected': 'N'},
            {'id': 'fa fa-envelope-o', 'text': 'fa fa-envelope-o', 'selected': 'N'},
            {'id': 'fa fa-heart', 'text': 'fa fa-heart', 'selected': 'N'},
            {'id': 'fa fa-star', 'text': 'fa fa-star', 'selected': 'N'},
            {'id': 'fa fa-star-o', 'text': 'fa fa-star-o', 'selected': 'N'},
            {'id': 'fa fa-user', 'text': 'fa fa-user', 'selected': 'N'},
            {'id': 'fa fa-film', 'text': 'fa fa-film', 'selected': 'N'},
            {'id': 'fa fa-th-large', 'text': 'fa fa-th-large', 'selected': 'N'},
            {'id': 'fa fa-th', 'text': 'fa fa-th', 'selected': 'N'},
            {'id': 'fa fa-th-list', 'text': 'fa fa-th-list', 'selected': 'N'},
            {'id': 'fa fa-check', 'text': 'fa fa-check', 'selected': 'N'},
            {'id': 'fa fa-remove', 'text': 'fa fa-remove', 'selected': 'N'},
            {'id': 'fa fa-close', 'text': 'fa fa-close', 'selected': 'N'},
            {'id': 'fa fa-times', 'text': 'fa fa-times', 'selected': 'N'},
            {'id': 'fa fa-search-plus', 'text': 'fa fa-search-plus', 'selected': 'N'},
            {'id': 'fa fa-search-minus', 'text': 'fa fa-search-minus', 'selected': 'N'},
            {'id': 'fa fa-power-off', 'text': 'fa fa-power-off', 'selected': 'N'},
            {'id': 'fa fa-signal', 'text': 'fa fa-signal', 'selected': 'N'},
            {'id': 'fa fa-gear', 'text': 'fa fa-gear', 'selected': 'N'},
            {'id': 'fa fa-cog', 'text': 'fa fa-cog', 'selected': 'N'},
            {'id': 'fa fa-trash-o', 'text': 'fa fa-trash-o', 'selected': 'N'},
            {'id': 'fa fa-home', 'text': 'fa fa-home', 'selected': 'N'},
            {'id': 'fa fa-file-o', 'text': 'fa fa-file-o', 'selected': 'N'},
            {'id': 'fa fa-clock-o', 'text': 'fa fa-clock-o', 'selected': 'N'},
            {'id': 'fa fa-road', 'text': 'fa fa-road', 'selected': 'N'},
            {'id': 'fa fa-download', 'text': 'fa fa-download', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-o-down', 'text': 'fa fa-arrow-circle-o-down', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-o-up', 'text': 'fa fa-arrow-circle-o-up', 'selected': 'N'},
            {'id': 'fa fa-inbox', 'text': 'fa fa-inbox', 'selected': 'N'},
            {'id': 'fa fa-play-circle-o', 'text': 'fa fa-play-circle-o', 'selected': 'N'},
            {'id': 'fa fa-rotate-right', 'text': 'fa fa-rotate-right', 'selected': 'N'},
            {'id': 'fa fa-repeat', 'text': 'fa fa-repeat', 'selected': 'N'},
            {'id': 'fa fa-refresh', 'text': 'fa fa-refresh', 'selected': 'N'},
            {'id': 'fa fa-list-alt', 'text': 'fa fa-list-alt', 'selected': 'N'},
            {'id': 'fa fa-lock', 'text': 'fa fa-lock', 'selected': 'N'},
            {'id': 'fa fa-flag', 'text': 'fa fa-flag', 'selected': 'N'},
            {'id': 'fa fa-headphones', 'text': 'fa fa-headphones', 'selected': 'N'},
            {'id': 'fa fa-volume-off', 'text': 'fa fa-volume-off', 'selected': 'N'},
            {'id': 'fa fa-volume-down', 'text': 'fa fa-volume-down', 'selected': 'N'},
            {'id': 'fa fa-volume-up', 'text': 'fa fa-volume-up', 'selected': 'N'},
            {'id': 'fa fa-qrcode', 'text': 'fa fa-qrcode', 'selected': 'N'},
            {'id': 'fa fa-barcode', 'text': 'fa fa-barcode', 'selected': 'N'},
            {'id': 'fa fa-tag', 'text': 'fa fa-tag', 'selected': 'N'},
            {'id': 'fa fa-tags', 'text': 'fa fa-tags', 'selected': 'N'},
            {'id': 'fa fa-book', 'text': 'fa fa-book', 'selected': 'N'},
            {'id': 'fa fa-bookmark', 'text': 'fa fa-bookmark', 'selected': 'N'},
            {'id': 'fa fa-print', 'text': 'fa fa-print', 'selected': 'N'},
            {'id': 'fa fa-camera', 'text': 'fa fa-camera', 'selected': 'N'},
            {'id': 'fa fa-font', 'text': 'fa fa-font', 'selected': 'N'},
            {'id': 'fa fa-bold', 'text': 'fa fa-bold', 'selected': 'N'},
            {'id': 'fa fa-italic', 'text': 'fa fa-italic', 'selected': 'N'},
            {'id': 'fa fa-text-height', 'text': 'fa fa-text-height', 'selected': 'N'},
            {'id': 'fa fa-text-width', 'text': 'fa fa-text-width', 'selected': 'N'},
            {'id': 'fa fa-align-left', 'text': 'fa fa-align-left', 'selected': 'N'},
            {'id': 'fa fa-align-center', 'text': 'fa fa-align-center', 'selected': 'N'},
            {'id': 'fa fa-align-right', 'text': 'fa fa-align-right', 'selected': 'N'},
            {'id': 'fa fa-align-justify', 'text': 'fa fa-align-justify', 'selected': 'N'},
            {'id': 'fa fa-list', 'text': 'fa fa-list', 'selected': 'N'},
            {'id': 'fa fa-dedent', 'text': 'fa fa-dedent', 'selected': 'N'},
            {'id': 'fa fa-outdent', 'text': 'fa fa-outdent', 'selected': 'N'},
            {'id': 'fa fa-indent', 'text': 'fa fa-indent', 'selected': 'N'},
            {'id': 'fa fa-video-camera', 'text': 'fa fa-video-camera', 'selected': 'N'},
            {'id': 'fa fa-photo', 'text': 'fa fa-photo', 'selected': 'N'},
            {'id': 'fa fa-image', 'text': 'fa fa-image', 'selected': 'N'},
            {'id': 'fa fa-picture-o', 'text': 'fa fa-picture-o', 'selected': 'N'},
            {'id': 'fa fa-pencil', 'text': 'fa fa-pencil', 'selected': 'N'},
            {'id': 'fa fa-map-marker', 'text': 'fa fa-map-marker', 'selected': 'N'},
            {'id': 'fa fa-adjust', 'text': 'fa fa-adjust', 'selected': 'N'},
            {'id': 'fa fa-tint', 'text': 'fa fa-tint', 'selected': 'N'},
            {'id': 'fa fa-edit', 'text': 'fa fa-edit', 'selected': 'N'},
            {'id': 'fa fa-pencil-square-o', 'text': 'fa fa-pencil-square-o', 'selected': 'N'},
            {'id': 'fa fa-share-square-o', 'text': 'fa fa-share-square-o', 'selected': 'N'},
            {'id': 'fa fa-check-square-o', 'text': 'fa fa-check-square-o', 'selected': 'N'},
            {'id': 'fa fa-arrows', 'text': 'fa fa-arrows', 'selected': 'N'},
            {'id': 'fa fa-step-backward', 'text': 'fa fa-step-backward', 'selected': 'N'},
            {'id': 'fa fa-fast-backward', 'text': 'fa fa-fast-backward', 'selected': 'N'},
            {'id': 'fa fa-backward', 'text': 'fa fa-backward', 'selected': 'N'},
            {'id': 'fa fa-play', 'text': 'fa fa-play', 'selected': 'N'},
            {'id': 'fa fa-pause', 'text': 'fa fa-pause', 'selected': 'N'},
            {'id': 'fa fa-stop', 'text': 'fa fa-stop', 'selected': 'N'},
            {'id': 'fa fa-forward', 'text': 'fa fa-forward', 'selected': 'N'},
            {'id': 'fa fa-fast-forward', 'text': 'fa fa-fast-forward', 'selected': 'N'},
            {'id': 'fa fa-step-forward', 'text': 'fa fa-step-forward', 'selected': 'N'},
            {'id': 'fa fa-eject', 'text': 'fa fa-eject', 'selected': 'N'},
            {'id': 'fa fa-chevron-left', 'text': 'fa fa-chevron-left', 'selected': 'N'},
            {'id': 'fa fa-chevron-right', 'text': 'fa fa-chevron-right', 'selected': 'N'},
            {'id': 'fa fa-plus-circle', 'text': 'fa fa-plus-circle', 'selected': 'N'},
            {'id': 'fa fa-minus-circle', 'text': 'fa fa-minus-circle', 'selected': 'N'},
            {'id': 'fa fa-times-circle', 'text': 'fa fa-times-circle', 'selected': 'N'},
            {'id': 'fa fa-check-circle', 'text': 'fa fa-check-circle', 'selected': 'N'},
            {'id': 'fa fa-question-circle', 'text': 'fa fa-question-circle', 'selected': 'N'},
            {'id': 'fa fa-info-circle', 'text': 'fa fa-info-circle', 'selected': 'N'},
            {'id': 'fa fa-crosshairs', 'text': 'fa fa-crosshairs', 'selected': 'N'},
            {'id': 'fa fa-times-circle-o', 'text': 'fa fa-times-circle-o', 'selected': 'N'},
            {'id': 'fa fa-check-circle-o', 'text': 'fa fa-check-circle-o', 'selected': 'N'},
            {'id': 'fa fa-ban', 'text': 'fa fa-ban', 'selected': 'N'},
            {'id': 'fa fa-arrow-left', 'text': 'fa fa-arrow-left', 'selected': 'N'},
            {'id': 'fa fa-arrow-right', 'text': 'fa fa-arrow-right', 'selected': 'N'},
            {'id': 'fa fa-arrow-up', 'text': 'fa fa-arrow-up', 'selected': 'N'},
            {'id': 'fa fa-arrow-down', 'text': 'fa fa-arrow-down', 'selected': 'N'},
            {'id': 'fa fa-mail-forward', 'text': 'fa fa-mail-forward', 'selected': 'N'},
            {'id': 'fa fa-share', 'text': 'fa fa-share', 'selected': 'N'},
            {'id': 'fa fa-expand', 'text': 'fa fa-expand', 'selected': 'N'},
            {'id': 'fa fa-compress', 'text': 'fa fa-compress', 'selected': 'N'},
            {'id': 'fa fa-plus', 'text': 'fa fa-plus', 'selected': 'N'},
            {'id': 'fa fa-minus', 'text': 'fa fa-minus', 'selected': 'N'},
            {'id': 'fa fa-asterisk', 'text': 'fa fa-asterisk', 'selected': 'N'},
            {'id': 'fa fa-exclamation-circle', 'text': 'fa fa-exclamation-circle', 'selected': 'N'},
            {'id': 'fa fa-gift', 'text': 'fa fa-gift', 'selected': 'N'},
            {'id': 'fa fa-leaf', 'text': 'fa fa-leaf', 'selected': 'N'},
            {'id': 'fa fa-fire', 'text': 'fa fa-fire', 'selected': 'N'},
            {'id': 'fa fa-eye', 'text': 'fa fa-eye', 'selected': 'N'},
            {'id': 'fa fa-eye-slash', 'text': 'fa fa-eye-slash', 'selected': 'N'},
            {'id': 'fa fa-warning', 'text': 'fa fa-warning', 'selected': 'N'},
            {'id': 'fa fa-exclamation-triangle', 'text': 'fa fa-exclamation-triangle', 'selected': 'N'},
            {'id': 'fa fa-plane', 'text': 'fa fa-plane', 'selected': 'N'},
            {'id': 'fa fa-calendar', 'text': 'fa fa-calendar', 'selected': 'N'},
            {'id': 'fa fa-random', 'text': 'fa fa-random', 'selected': 'N'},
            {'id': 'fa fa-comment', 'text': 'fa fa-comment', 'selected': 'N'},
            {'id': 'fa fa-magnet', 'text': 'fa fa-magnet', 'selected': 'N'},
            {'id': 'fa fa-chevron-up', 'text': 'fa fa-chevron-up', 'selected': 'N'},
            {'id': 'fa fa-chevron-down', 'text': 'fa fa-chevron-down', 'selected': 'N'},
            {'id': 'fa fa-retweet', 'text': 'fa fa-retweet', 'selected': 'N'},
            {'id': 'fa fa-shopping-cart', 'text': 'fa fa-shopping-cart', 'selected': 'N'},
            {'id': 'fa fa-folder', 'text': 'fa fa-folder', 'selected': 'N'},
            {'id': 'fa fa-folder-open', 'text': 'fa fa-folder-open', 'selected': 'N'},
            {'id': 'fa fa-arrows-v', 'text': 'fa fa-arrows-v', 'selected': 'N'},
            {'id': 'fa fa-arrows-h', 'text': 'fa fa-arrows-h', 'selected': 'N'},
            {'id': 'fa fa-bar-chart-o', 'text': 'fa fa-bar-chart-o', 'selected': 'N'},
            {'id': 'fa fa-bar-chart', 'text': 'fa fa-bar-chart', 'selected': 'N'},
            {'id': 'fa fa-twitter-square', 'text': 'fa fa-twitter-square', 'selected': 'N'},
            {'id': 'fa fa-facebook-square', 'text': 'fa fa-facebook-square', 'selected': 'N'},
            {'id': 'fa fa-camera-retro', 'text': 'fa fa-camera-retro', 'selected': 'N'},
            {'id': 'fa fa-key', 'text': 'fa fa-key', 'selected': 'N'},
            {'id': 'fa fa-gears', 'text': 'fa fa-gears', 'selected': 'N'},
            {'id': 'fa fa-cogs', 'text': 'fa fa-cogs', 'selected': 'N'},
            {'id': 'fa fa-comments', 'text': 'fa fa-comments', 'selected': 'N'},
            {'id': 'fa fa-thumbs-o-up', 'text': 'fa fa-thumbs-o-up', 'selected': 'N'},
            {'id': 'fa fa-thumbs-o-down', 'text': 'fa fa-thumbs-o-down', 'selected': 'N'},
            {'id': 'fa fa-star-half', 'text': 'fa fa-star-half', 'selected': 'N'},
            {'id': 'fa fa-heart-o', 'text': 'fa fa-heart-o', 'selected': 'N'},
            {'id': 'fa fa-sign-out', 'text': 'fa fa-sign-out', 'selected': 'N'},
            {'id': 'fa fa-linkedin-square', 'text': 'fa fa-linkedin-square', 'selected': 'N'},
            {'id': 'fa fa-thumb-tack', 'text': 'fa fa-thumb-tack', 'selected': 'N'},
            {'id': 'fa fa-external-link', 'text': 'fa fa-external-link', 'selected': 'N'},
            {'id': 'fa fa-sign-in', 'text': 'fa fa-sign-in', 'selected': 'N'},
            {'id': 'fa fa-trophy', 'text': 'fa fa-trophy', 'selected': 'N'},
            {'id': 'fa fa-github-square', 'text': 'fa fa-github-square', 'selected': 'N'},
            {'id': 'fa fa-upload', 'text': 'fa fa-upload', 'selected': 'N'},
            {'id': 'fa fa-lemon-o', 'text': 'fa fa-lemon-o', 'selected': 'N'},
            {'id': 'fa fa-phone', 'text': 'fa fa-phone', 'selected': 'N'},
            {'id': 'fa fa-square-o', 'text': 'fa fa-square-o', 'selected': 'N'},
            {'id': 'fa fa-bookmark-o', 'text': 'fa fa-bookmark-o', 'selected': 'N'},
            {'id': 'fa fa-phone-square', 'text': 'fa fa-phone-square', 'selected': 'N'},
            {'id': 'fa fa-twitter', 'text': 'fa fa-twitter', 'selected': 'N'},
            {'id': 'fa fa-facebook-f', 'text': 'fa fa-facebook-f', 'selected': 'N'},
            {'id': 'fa fa-facebook', 'text': 'fa fa-facebook', 'selected': 'N'},
            {'id': 'fa fa-github', 'text': 'fa fa-github', 'selected': 'N'},
            {'id': 'fa fa-unlock', 'text': 'fa fa-unlock', 'selected': 'N'},
            {'id': 'fa fa-credit-card', 'text': 'fa fa-credit-card', 'selected': 'N'},
            {'id': 'fa fa-rss', 'text': 'fa fa-rss', 'selected': 'N'},
            {'id': 'fa fa-hdd-o', 'text': 'fa fa-hdd-o', 'selected': 'N'},
            {'id': 'fa fa-bullhorn', 'text': 'fa fa-bullhorn', 'selected': 'N'},
            {'id': 'fa fa-bell', 'text': 'fa fa-bell', 'selected': 'N'},
            {'id': 'fa fa-certificate', 'text': 'fa fa-certificate', 'selected': 'N'},
            {'id': 'fa fa-hand-o-right', 'text': 'fa fa-hand-o-right', 'selected': 'N'},
            {'id': 'fa fa-hand-o-left', 'text': 'fa fa-hand-o-left', 'selected': 'N'},
            {'id': 'fa fa-hand-o-up', 'text': 'fa fa-hand-o-up', 'selected': 'N'},
            {'id': 'fa fa-hand-o-down', 'text': 'fa fa-hand-o-down', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-left', 'text': 'fa fa-arrow-circle-left', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-right', 'text': 'fa fa-arrow-circle-right', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-up', 'text': 'fa fa-arrow-circle-up', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-down', 'text': 'fa fa-arrow-circle-down', 'selected': 'N'},
            {'id': 'fa fa-globe', 'text': 'fa fa-globe', 'selected': 'N'},
            {'id': 'fa fa-wrench', 'text': 'fa fa-wrench', 'selected': 'N'},
            {'id': 'fa fa-tasks', 'text': 'fa fa-tasks', 'selected': 'N'},
            {'id': 'fa fa-filter', 'text': 'fa fa-filter', 'selected': 'N'},
            {'id': 'fa fa-briefcase', 'text': 'fa fa-briefcase', 'selected': 'N'},
            {'id': 'fa fa-arrows-alt', 'text': 'fa fa-arrows-alt', 'selected': 'N'},
            {'id': 'fa fa-group', 'text': 'fa fa-group', 'selected': 'N'},
            {'id': 'fa fa-users', 'text': 'fa fa-users', 'selected': 'N'},
            {'id': 'fa fa-chain', 'text': 'fa fa-chain', 'selected': 'N'},
            {'id': 'fa fa-link', 'text': 'fa fa-link', 'selected': 'N'},
            {'id': 'fa fa-cloud', 'text': 'fa fa-cloud', 'selected': 'N'},
            {'id': 'fa fa-flask', 'text': 'fa fa-flask', 'selected': 'N'},
            {'id': 'fa fa-cut', 'text': 'fa fa-cut', 'selected': 'N'},
            {'id': 'fa fa-scissors', 'text': 'fa fa-scissors', 'selected': 'N'},
            {'id': 'fa fa-copy', 'text': 'fa fa-copy', 'selected': 'N'},
            {'id': 'fa fa-files-o', 'text': 'fa fa-files-o', 'selected': 'N'},
            {'id': 'fa fa-paperclip', 'text': 'fa fa-paperclip', 'selected': 'N'},
            {'id': 'fa fa-save', 'text': 'fa fa-save', 'selected': 'N'},
            {'id': 'fa fa-floppy-o', 'text': 'fa fa-floppy-o', 'selected': 'N'},
            {'id': 'fa fa-square', 'text': 'fa fa-square', 'selected': 'N'},
            {'id': 'fa fa-navicon', 'text': 'fa fa-navicon', 'selected': 'N'},
            {'id': 'fa fa-reorder', 'text': 'fa fa-reorder', 'selected': 'N'},
            {'id': 'fa fa-bars', 'text': 'fa fa-bars', 'selected': 'N'},
            {'id': 'fa fa-list-ul', 'text': 'fa fa-list-ul', 'selected': 'N'},
            {'id': 'fa fa-list-ol', 'text': 'fa fa-list-ol', 'selected': 'N'},
            {'id': 'fa fa-strikethrough', 'text': 'fa fa-strikethrough', 'selected': 'N'},
            {'id': 'fa fa-underline', 'text': 'fa fa-underline', 'selected': 'N'},
            {'id': 'fa fa-table', 'text': 'fa fa-table', 'selected': 'N'},
            {'id': 'fa fa-magic', 'text': 'fa fa-magic', 'selected': 'N'},
            {'id': 'fa fa-truck', 'text': 'fa fa-truck', 'selected': 'N'},
            {'id': 'fa fa-pinterest', 'text': 'fa fa-pinterest', 'selected': 'N'},
            {'id': 'fa fa-pinterest-square', 'text': 'fa fa-pinterest-square', 'selected': 'N'},
            {'id': 'fa fa-google-plus-square', 'text': 'fa fa-google-plus-square', 'selected': 'N'},
            {'id': 'fa fa-google-plus', 'text': 'fa fa-google-plus', 'selected': 'N'},
            {'id': 'fa fa-money', 'text': 'fa fa-money', 'selected': 'N'},
            {'id': 'fa fa-caret-down', 'text': 'fa fa-caret-down', 'selected': 'N'},
            {'id': 'fa fa-caret-up', 'text': 'fa fa-caret-up', 'selected': 'N'},
            {'id': 'fa fa-caret-left', 'text': 'fa fa-caret-left', 'selected': 'N'},
            {'id': 'fa fa-caret-right', 'text': 'fa fa-caret-right', 'selected': 'N'},
            {'id': 'fa fa-columns', 'text': 'fa fa-columns', 'selected': 'N'},
            {'id': 'fa fa-unsorted', 'text': 'fa fa-unsorted', 'selected': 'N'},
            {'id': 'fa fa-sort', 'text': 'fa fa-sort', 'selected': 'N'},
            {'id': 'fa fa-sort-down', 'text': 'fa fa-sort-down', 'selected': 'N'},
            {'id': 'fa fa-sort-desc', 'text': 'fa fa-sort-desc', 'selected': 'N'},
            {'id': 'fa fa-sort-up', 'text': 'fa fa-sort-up', 'selected': 'N'},
            {'id': 'fa fa-sort-asc', 'text': 'fa fa-sort-asc', 'selected': 'N'},
            {'id': 'fa fa-envelope', 'text': 'fa fa-envelope', 'selected': 'N'},
            {'id': 'fa fa-linkedin', 'text': 'fa fa-linkedin', 'selected': 'N'},
            {'id': 'fa fa-rotate-left', 'text': 'fa fa-rotate-left', 'selected': 'N'},
            {'id': 'fa fa-undo', 'text': 'fa fa-undo', 'selected': 'N'},
            {'id': 'fa fa-legal', 'text': 'fa fa-legal', 'selected': 'N'},
            {'id': 'fa fa-gavel', 'text': 'fa fa-gavel', 'selected': 'N'},
            {'id': 'fa fa-dashboard', 'text': 'fa fa-dashboard', 'selected': 'N'},
            {'id': 'fa fa-tachometer', 'text': 'fa fa-tachometer', 'selected': 'N'},
            {'id': 'fa fa-comment-o', 'text': 'fa fa-comment-o', 'selected': 'N'},
            {'id': 'fa fa-comments-o', 'text': 'fa fa-comments-o', 'selected': 'N'},
            {'id': 'fa fa-flash', 'text': 'fa fa-flash', 'selected': 'N'},
            {'id': 'fa fa-bolt', 'text': 'fa fa-bolt', 'selected': 'N'},
            {'id': 'fa fa-sitemap', 'text': 'fa fa-sitemap', 'selected': 'N'},
            {'id': 'fa fa-umbrella', 'text': 'fa fa-umbrella', 'selected': 'N'},
            {'id': 'fa fa-paste', 'text': 'fa fa-paste', 'selected': 'N'},
            {'id': 'fa fa-clipboard', 'text': 'fa fa-clipboard', 'selected': 'N'},
            {'id': 'fa fa-lightbulb-o', 'text': 'fa fa-lightbulb-o', 'selected': 'N'},
            {'id': 'fa fa-exchange', 'text': 'fa fa-exchange', 'selected': 'N'},
            {'id': 'fa fa-cloud-download', 'text': 'fa fa-cloud-download', 'selected': 'N'},
            {'id': 'fa fa-cloud-upload', 'text': 'fa fa-cloud-upload', 'selected': 'N'},
            {'id': 'fa fa-user-md', 'text': 'fa fa-user-md', 'selected': 'N'},
            {'id': 'fa fa-stethoscope', 'text': 'fa fa-stethoscope', 'selected': 'N'},
            {'id': 'fa fa-suitcase', 'text': 'fa fa-suitcase', 'selected': 'N'},
            {'id': 'fa fa-bell-o', 'text': 'fa fa-bell-o', 'selected': 'N'},
            {'id': 'fa fa-coffee', 'text': 'fa fa-coffee', 'selected': 'N'},
            {'id': 'fa fa-cutlery', 'text': 'fa fa-cutlery', 'selected': 'N'},
            {'id': 'fa fa-file-text-o', 'text': 'fa fa-file-text-o', 'selected': 'N'},
            {'id': 'fa fa-building-o', 'text': 'fa fa-building-o', 'selected': 'N'},
            {'id': 'fa fa-hospital-o', 'text': 'fa fa-hospital-o', 'selected': 'N'},
            {'id': 'fa fa-ambulance', 'text': 'fa fa-ambulance', 'selected': 'N'},
            {'id': 'fa fa-medkit', 'text': 'fa fa-medkit', 'selected': 'N'},
            {'id': 'fa fa-fighter-jet', 'text': 'fa fa-fighter-jet', 'selected': 'N'},
            {'id': 'fa fa-beer', 'text': 'fa fa-beer', 'selected': 'N'},
            {'id': 'fa fa-h-square', 'text': 'fa fa-h-square', 'selected': 'N'},
            {'id': 'fa fa-plus-square', 'text': 'fa fa-plus-square', 'selected': 'N'},
            {'id': 'fa fa-angle-double-left', 'text': 'fa fa-angle-double-left', 'selected': 'N'},
            {'id': 'fa fa-angle-double-right', 'text': 'fa fa-angle-double-right', 'selected': 'N'},
            {'id': 'fa fa-angle-double-up', 'text': 'fa fa-angle-double-up', 'selected': 'N'},
            {'id': 'fa fa-angle-double-down', 'text': 'fa fa-angle-double-down', 'selected': 'N'},
            {'id': 'fa fa-angle-left', 'text': 'fa fa-angle-left', 'selected': 'N'},
            {'id': 'fa fa-angle-right', 'text': 'fa fa-angle-right', 'selected': 'N'},
            {'id': 'fa fa-angle-up', 'text': 'fa fa-angle-up', 'selected': 'N'},
            {'id': 'fa fa-angle-down', 'text': 'fa fa-angle-down', 'selected': 'N'},
            {'id': 'fa fa-desktop', 'text': 'fa fa-desktop', 'selected': 'N'},
            {'id': 'fa fa-laptop', 'text': 'fa fa-laptop', 'selected': 'N'},
            {'id': 'fa fa-tablet', 'text': 'fa fa-tablet', 'selected': 'N'},
            {'id': 'fa fa-mobile-phone', 'text': 'fa fa-mobile-phone', 'selected': 'N'},
            {'id': 'fa fa-mobile', 'text': 'fa fa-mobile', 'selected': 'N'},
            {'id': 'fa fa-circle-o', 'text': 'fa fa-circle-o', 'selected': 'N'},
            {'id': 'fa fa-quote-left', 'text': 'fa fa-quote-left', 'selected': 'N'},
            {'id': 'fa fa-quote-right', 'text': 'fa fa-quote-right', 'selected': 'N'},
            {'id': 'fa fa-spinner', 'text': 'fa fa-spinner', 'selected': 'N'},
            {'id': 'fa fa-circle', 'text': 'fa fa-circle', 'selected': 'N'},
            {'id': 'fa fa-mail-reply', 'text': 'fa fa-mail-reply', 'selected': 'N'},
            {'id': 'fa fa-reply', 'text': 'fa fa-reply', 'selected': 'N'},
            {'id': 'fa fa-github-alt', 'text': 'fa fa-github-alt', 'selected': 'N'},
            {'id': 'fa fa-folder-o', 'text': 'fa fa-folder-o', 'selected': 'N'},
            {'id': 'fa fa-folder-open-o', 'text': 'fa fa-folder-open-o', 'selected': 'N'},
            {'id': 'fa fa-smile-o', 'text': 'fa fa-smile-o', 'selected': 'N'},
            {'id': 'fa fa-frown-o', 'text': 'fa fa-frown-o', 'selected': 'N'},
            {'id': 'fa fa-meh-o', 'text': 'fa fa-meh-o', 'selected': 'N'},
            {'id': 'fa fa-gamepad', 'text': 'fa fa-gamepad', 'selected': 'N'},
            {'id': 'fa fa-keyboard-o', 'text': 'fa fa-keyboard-o', 'selected': 'N'},
            {'id': 'fa fa-flag-o', 'text': 'fa fa-flag-o', 'selected': 'N'},
            {'id': 'fa fa-flag-checkered', 'text': 'fa fa-flag-checkered', 'selected': 'N'},
            {'id': 'fa fa-terminal', 'text': 'fa fa-terminal', 'selected': 'N'},
            {'id': 'fa fa-code', 'text': 'fa fa-code', 'selected': 'N'},
            {'id': 'fa fa-mail-reply-all', 'text': 'fa fa-mail-reply-all', 'selected': 'N'},
            {'id': 'fa fa-reply-all', 'text': 'fa fa-reply-all', 'selected': 'N'},
            {'id': 'fa fa-star-half-empty', 'text': 'fa fa-star-half-empty', 'selected': 'N'},
            {'id': 'fa fa-star-half-full', 'text': 'fa fa-star-half-full', 'selected': 'N'},
            {'id': 'fa fa-star-half-o', 'text': 'fa fa-star-half-o', 'selected': 'N'},
            {'id': 'fa fa-location-arrow', 'text': 'fa fa-location-arrow', 'selected': 'N'},
            {'id': 'fa fa-crop', 'text': 'fa fa-crop', 'selected': 'N'},
            {'id': 'fa fa-code-fork', 'text': 'fa fa-code-fork', 'selected': 'N'},
            {'id': 'fa fa-unlink', 'text': 'fa fa-unlink', 'selected': 'N'},
            {'id': 'fa fa-chain-broken', 'text': 'fa fa-chain-broken', 'selected': 'N'},
            {'id': 'fa fa-question', 'text': 'fa fa-question', 'selected': 'N'},
            {'id': 'fa fa-info', 'text': 'fa fa-info', 'selected': 'N'},
            {'id': 'fa fa-exclamation', 'text': 'fa fa-exclamation', 'selected': 'N'},
            {'id': 'fa fa-superscript', 'text': 'fa fa-superscript', 'selected': 'N'},
            {'id': 'fa fa-subscript', 'text': 'fa fa-subscript', 'selected': 'N'},
            {'id': 'fa fa-eraser', 'text': 'fa fa-eraser', 'selected': 'N'},
            {'id': 'fa fa-puzzle-piece', 'text': 'fa fa-puzzle-piece', 'selected': 'N'},
            {'id': 'fa fa-microphone', 'text': 'fa fa-microphone', 'selected': 'N'},
            {'id': 'fa fa-microphone-slash', 'text': 'fa fa-microphone-slash', 'selected': 'N'},
            {'id': 'fa fa-shield', 'text': 'fa fa-shield', 'selected': 'N'},
            {'id': 'fa fa-calendar-o', 'text': 'fa fa-calendar-o', 'selected': 'N'},
            {'id': 'fa fa-fire-extinguisher', 'text': 'fa fa-fire-extinguisher', 'selected': 'N'},
            {'id': 'fa fa-rocket', 'text': 'fa fa-rocket', 'selected': 'N'},
            {'id': 'fa fa-maxcdn', 'text': 'fa fa-maxcdn', 'selected': 'N'},
            {'id': 'fa fa-chevron-circle-left', 'text': 'fa fa-chevron-circle-left', 'selected': 'N'},
            {'id': 'fa fa-chevron-circle-right', 'text': 'fa fa-chevron-circle-right', 'selected': 'N'},
            {'id': 'fa fa-chevron-circle-up', 'text': 'fa fa-chevron-circle-up', 'selected': 'N'},
            {'id': 'fa fa-chevron-circle-down', 'text': 'fa fa-chevron-circle-down', 'selected': 'N'},
            {'id': 'fa fa-html5', 'text': 'fa fa-html5', 'selected': 'N'},
            {'id': 'fa fa-css3', 'text': 'fa fa-css3', 'selected': 'N'},
            {'id': 'fa fa-anchor', 'text': 'fa fa-anchor', 'selected': 'N'},
            {'id': 'fa fa-unlock-alt', 'text': 'fa fa-unlock-alt', 'selected': 'N'},
            {'id': 'fa fa-bullseye', 'text': 'fa fa-bullseye', 'selected': 'N'},
            {'id': 'fa fa-ellipsis-h', 'text': 'fa fa-ellipsis-h', 'selected': 'N'},
            {'id': 'fa fa-ellipsis-v', 'text': 'fa fa-ellipsis-v', 'selected': 'N'},
            {'id': 'fa fa-rss-square', 'text': 'fa fa-rss-square', 'selected': 'N'},
            {'id': 'fa fa-play-circle', 'text': 'fa fa-play-circle', 'selected': 'N'},
            {'id': 'fa fa-ticket', 'text': 'fa fa-ticket', 'selected': 'N'},
            {'id': 'fa fa-minus-square', 'text': 'fa fa-minus-square', 'selected': 'N'},
            {'id': 'fa fa-minus-square-o', 'text': 'fa fa-minus-square-o', 'selected': 'N'},
            {'id': 'fa fa-level-up', 'text': 'fa fa-level-up', 'selected': 'N'},
            {'id': 'fa fa-level-down', 'text': 'fa fa-level-down', 'selected': 'N'},
            {'id': 'fa fa-check-square', 'text': 'fa fa-check-square', 'selected': 'N'},
            {'id': 'fa fa-pencil-square', 'text': 'fa fa-pencil-square', 'selected': 'N'},
            {'id': 'fa fa-external-link-square', 'text': 'fa fa-external-link-square', 'selected': 'N'},
            {'id': 'fa fa-share-square', 'text': 'fa fa-share-square', 'selected': 'N'},
            {'id': 'fa fa-compass', 'text': 'fa fa-compass', 'selected': 'N'},
            {'id': 'fa fa-toggle-down', 'text': 'fa fa-toggle-down', 'selected': 'N'},
            {'id': 'fa fa-caret-square-o-down', 'text': 'fa fa-caret-square-o-down', 'selected': 'N'},
            {'id': 'fa fa-toggle-up', 'text': 'fa fa-toggle-up', 'selected': 'N'},
            {'id': 'fa fa-caret-square-o-up', 'text': 'fa fa-caret-square-o-up', 'selected': 'N'},
            {'id': 'fa fa-toggle-right', 'text': 'fa fa-toggle-right', 'selected': 'N'},
            {'id': 'fa fa-caret-square-o-right', 'text': 'fa fa-caret-square-o-right', 'selected': 'N'},
            {'id': 'fa fa-euro', 'text': 'fa fa-euro', 'selected': 'N'},
            {'id': 'fa fa-eur', 'text': 'fa fa-eur', 'selected': 'N'},
            {'id': 'fa fa-gbp', 'text': 'fa fa-gbp', 'selected': 'N'},
            {'id': 'fa fa-dollar', 'text': 'fa fa-dollar', 'selected': 'N'},
            {'id': 'fa fa-usd', 'text': 'fa fa-usd', 'selected': 'N'},
            {'id': 'fa fa-rupee', 'text': 'fa fa-rupee', 'selected': 'N'},
            {'id': 'fa fa-inr', 'text': 'fa fa-inr', 'selected': 'N'},
            {'id': 'fa fa-cny', 'text': 'fa fa-cny', 'selected': 'N'},
            {'id': 'fa fa-rmb', 'text': 'fa fa-rmb', 'selected': 'N'},
            {'id': 'fa fa-yen', 'text': 'fa fa-yen', 'selected': 'N'},
            {'id': 'fa fa-jpy', 'text': 'fa fa-jpy', 'selected': 'N'},
            {'id': 'fa fa-ruble', 'text': 'fa fa-ruble', 'selected': 'N'},
            {'id': 'fa fa-rouble', 'text': 'fa fa-rouble', 'selected': 'N'},
            {'id': 'fa fa-rub', 'text': 'fa fa-rub', 'selected': 'N'},
            {'id': 'fa fa-won', 'text': 'fa fa-won', 'selected': 'N'},
            {'id': 'fa fa-krw', 'text': 'fa fa-krw', 'selected': 'N'},
            {'id': 'fa fa-bitcoin', 'text': 'fa fa-bitcoin', 'selected': 'N'},
            {'id': 'fa fa-btc', 'text': 'fa fa-btc', 'selected': 'N'},
            {'id': 'fa fa-file', 'text': 'fa fa-file', 'selected': 'N'},
            {'id': 'fa fa-file-text', 'text': 'fa fa-file-text', 'selected': 'N'},
            {'id': 'fa fa-sort-alpha-asc', 'text': 'fa fa-sort-alpha-asc', 'selected': 'N'},
            {'id': 'fa fa-sort-alpha-desc', 'text': 'fa fa-sort-alpha-desc', 'selected': 'N'},
            {'id': 'fa fa-sort-amount-asc', 'text': 'fa fa-sort-amount-asc', 'selected': 'N'},
            {'id': 'fa fa-sort-amount-desc', 'text': 'fa fa-sort-amount-desc', 'selected': 'N'},
            {'id': 'fa fa-sort-numeric-asc', 'text': 'fa fa-sort-numeric-asc', 'selected': 'N'},
            {'id': 'fa fa-sort-numeric-desc', 'text': 'fa fa-sort-numeric-desc', 'selected': 'N'},
            {'id': 'fa fa-thumbs-up', 'text': 'fa fa-thumbs-up', 'selected': 'N'},
            {'id': 'fa fa-thumbs-down', 'text': 'fa fa-thumbs-down', 'selected': 'N'},
            {'id': 'fa fa-youtube-square', 'text': 'fa fa-youtube-square', 'selected': 'N'},
            {'id': 'fa fa-youtube', 'text': 'fa fa-youtube', 'selected': 'N'},
            {'id': 'fa fa-xing', 'text': 'fa fa-xing', 'selected': 'N'},
            {'id': 'fa fa-xing-square', 'text': 'fa fa-xing-square', 'selected': 'N'},
            {'id': 'fa fa-youtube-play', 'text': 'fa fa-youtube-play', 'selected': 'N'},
            {'id': 'fa fa-dropbox', 'text': 'fa fa-dropbox', 'selected': 'N'},
            {'id': 'fa fa-stack-overflow', 'text': 'fa fa-stack-overflow', 'selected': 'N'},
            {'id': 'fa fa-instagram', 'text': 'fa fa-instagram', 'selected': 'N'},
            {'id': 'fa fa-flickr', 'text': 'fa fa-flickr', 'selected': 'N'},
            {'id': 'fa fa-adn', 'text': 'fa fa-adn', 'selected': 'N'},
            {'id': 'fa fa-bitbucket', 'text': 'fa fa-bitbucket', 'selected': 'N'},
            {'id': 'fa fa-bitbucket-square', 'text': 'fa fa-bitbucket-square', 'selected': 'N'},
            {'id': 'fa fa-tumblr', 'text': 'fa fa-tumblr', 'selected': 'N'},
            {'id': 'fa fa-tumblr-square', 'text': 'fa fa-tumblr-square', 'selected': 'N'},
            {'id': 'fa fa-long-arrow-down', 'text': 'fa fa-long-arrow-down', 'selected': 'N'},
            {'id': 'fa fa-long-arrow-up', 'text': 'fa fa-long-arrow-up', 'selected': 'N'},
            {'id': 'fa fa-long-arrow-left', 'text': 'fa fa-long-arrow-left', 'selected': 'N'},
            {'id': 'fa fa-long-arrow-right', 'text': 'fa fa-long-arrow-right', 'selected': 'N'},
            {'id': 'fa fa-apple', 'text': 'fa fa-apple', 'selected': 'N'},
            {'id': 'fa fa-windows', 'text': 'fa fa-windows', 'selected': 'N'},
            {'id': 'fa fa-android', 'text': 'fa fa-android', 'selected': 'N'},
            {'id': 'fa fa-linux', 'text': 'fa fa-linux', 'selected': 'N'},
            {'id': 'fa fa-dribbble', 'text': 'fa fa-dribbble', 'selected': 'N'},
            {'id': 'fa fa-skype', 'text': 'fa fa-skype', 'selected': 'N'},
            {'id': 'fa fa-foursquare', 'text': 'fa fa-foursquare', 'selected': 'N'},
            {'id': 'fa fa-trello', 'text': 'fa fa-trello', 'selected': 'N'},
            {'id': 'fa fa-female', 'text': 'fa fa-female', 'selected': 'N'},
            {'id': 'fa fa-male', 'text': 'fa fa-male', 'selected': 'N'},
            {'id': 'fa fa-gittip', 'text': 'fa fa-gittip', 'selected': 'N'},
            {'id': 'fa fa-gratipay', 'text': 'fa fa-gratipay', 'selected': 'N'},
            {'id': 'fa fa-sun-o', 'text': 'fa fa-sun-o', 'selected': 'N'},
            {'id': 'fa fa-moon-o', 'text': 'fa fa-moon-o', 'selected': 'N'},
            {'id': 'fa fa-archive', 'text': 'fa fa-archive', 'selected': 'N'},
            {'id': 'fa fa-bug', 'text': 'fa fa-bug', 'selected': 'N'},
            {'id': 'fa fa-vk', 'text': 'fa fa-vk', 'selected': 'N'},
            {'id': 'fa fa-weibo', 'text': 'fa fa-weibo', 'selected': 'N'},
            {'id': 'fa fa-renren', 'text': 'fa fa-renren', 'selected': 'N'},
            {'id': 'fa fa-pagelines', 'text': 'fa fa-pagelines', 'selected': 'N'},
            {'id': 'fa fa-stack-exchange', 'text': 'fa fa-stack-exchange', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-o-right', 'text': 'fa fa-arrow-circle-o-right', 'selected': 'N'},
            {'id': 'fa fa-arrow-circle-o-left', 'text': 'fa fa-arrow-circle-o-left', 'selected': 'N'},
            {'id': 'fa fa-toggle-left', 'text': 'fa fa-toggle-left', 'selected': 'N'},
            {'id': 'fa fa-caret-square-o-left', 'text': 'fa fa-caret-square-o-left', 'selected': 'N'},
            {'id': 'fa fa-dot-circle-o', 'text': 'fa fa-dot-circle-o', 'selected': 'N'},
            {'id': 'fa fa-wheelchair', 'text': 'fa fa-wheelchair', 'selected': 'N'},
            {'id': 'fa fa-vimeo-square', 'text': 'fa fa-vimeo-square', 'selected': 'N'},
            {'id': 'fa fa-turkish-lira', 'text': 'fa fa-turkish-lira', 'selected': 'N'},
            {'id': 'fa fa-try', 'text': 'fa fa-try', 'selected': 'N'},
            {'id': 'fa fa-plus-square-o', 'text': 'fa fa-plus-square-o', 'selected': 'N'},
            {'id': 'fa fa-space-shuttle', 'text': 'fa fa-space-shuttle', 'selected': 'N'},
            {'id': 'fa fa-slack', 'text': 'fa fa-slack', 'selected': 'N'},
            {'id': 'fa fa-envelope-square', 'text': 'fa fa-envelope-square', 'selected': 'N'},
            {'id': 'fa fa-wordpress', 'text': 'fa fa-wordpress', 'selected': 'N'},
            {'id': 'fa fa-openid', 'text': 'fa fa-openid', 'selected': 'N'},
            {'id': 'fa fa-institution', 'text': 'fa fa-institution', 'selected': 'N'},
            {'id': 'fa fa-bank', 'text': 'fa fa-bank', 'selected': 'N'},
            {'id': 'fa fa-university', 'text': 'fa fa-university', 'selected': 'N'},
            {'id': 'fa fa-mortar-board', 'text': 'fa fa-mortar-board', 'selected': 'N'},
            {'id': 'fa fa-graduation-cap', 'text': 'fa fa-graduation-cap', 'selected': 'N'},
            {'id': 'fa fa-yahoo', 'text': 'fa fa-yahoo', 'selected': 'N'},
            {'id': 'fa fa-google', 'text': 'fa fa-google', 'selected': 'N'},
            {'id': 'fa fa-reddit', 'text': 'fa fa-reddit', 'selected': 'N'},
            {'id': 'fa fa-reddit-square', 'text': 'fa fa-reddit-square', 'selected': 'N'},
            {'id': 'fa fa-stumbleupon-circle', 'text': 'fa fa-stumbleupon-circle', 'selected': 'N'},
            {'id': 'fa fa-stumbleupon', 'text': 'fa fa-stumbleupon', 'selected': 'N'},
            {'id': 'fa fa-delicious', 'text': 'fa fa-delicious', 'selected': 'N'},
            {'id': 'fa fa-digg', 'text': 'fa fa-digg', 'selected': 'N'},
            {'id': 'fa fa-pied-piper', 'text': 'fa fa-pied-piper', 'selected': 'N'},
            {'id': 'fa fa-pied-piper-alt', 'text': 'fa fa-pied-piper-alt', 'selected': 'N'},
            {'id': 'fa fa-drupal', 'text': 'fa fa-drupal', 'selected': 'N'},
            {'id': 'fa fa-joomla', 'text': 'fa fa-joomla', 'selected': 'N'},
            {'id': 'fa fa-language', 'text': 'fa fa-language', 'selected': 'N'},
            {'id': 'fa fa-fax', 'text': 'fa fa-fax', 'selected': 'N'},
            {'id': 'fa fa-building', 'text': 'fa fa-building', 'selected': 'N'},
            {'id': 'fa fa-child', 'text': 'fa fa-child', 'selected': 'N'},
            {'id': 'fa fa-paw', 'text': 'fa fa-paw', 'selected': 'N'},
            {'id': 'fa fa-spoon', 'text': 'fa fa-spoon', 'selected': 'N'},
            {'id': 'fa fa-cube', 'text': 'fa fa-cube', 'selected': 'N'},
            {'id': 'fa fa-cubes', 'text': 'fa fa-cubes', 'selected': 'N'},
            {'id': 'fa fa-behance', 'text': 'fa fa-behance', 'selected': 'N'},
            {'id': 'fa fa-behance-square', 'text': 'fa fa-behance-square', 'selected': 'N'},
            {'id': 'fa fa-steam', 'text': 'fa fa-steam', 'selected': 'N'},
            {'id': 'fa fa-steam-square', 'text': 'fa fa-steam-square', 'selected': 'N'},
            {'id': 'fa fa-recycle', 'text': 'fa fa-recycle', 'selected': 'N'},
            {'id': 'fa fa-automobile', 'text': 'fa fa-automobile', 'selected': 'N'},
            {'id': 'fa fa-car', 'text': 'fa fa-car', 'selected': 'N'},
            {'id': 'fa fa-cab', 'text': 'fa fa-cab', 'selected': 'N'},
            {'id': 'fa fa-taxi', 'text': 'fa fa-taxi', 'selected': 'N'},
            {'id': 'fa fa-tree', 'text': 'fa fa-tree', 'selected': 'N'},
            {'id': 'fa fa-spotify', 'text': 'fa fa-spotify', 'selected': 'N'},
            {'id': 'fa fa-deviantart', 'text': 'fa fa-deviantart', 'selected': 'N'},
            {'id': 'fa fa-soundcloud', 'text': 'fa fa-soundcloud', 'selected': 'N'},
            {'id': 'fa fa-database', 'text': 'fa fa-database', 'selected': 'N'},
            {'id': 'fa fa-file-pdf-o', 'text': 'fa fa-file-pdf-o', 'selected': 'N'},
            {'id': 'fa fa-file-word-o', 'text': 'fa fa-file-word-o', 'selected': 'N'},
            {'id': 'fa fa-file-excel-o', 'text': 'fa fa-file-excel-o', 'selected': 'N'},
            {'id': 'fa fa-file-powerpoint-o', 'text': 'fa fa-file-powerpoint-o', 'selected': 'N'},
            {'id': 'fa fa-file-photo-o', 'text': 'fa fa-file-photo-o', 'selected': 'N'},
            {'id': 'fa fa-file-picture-o', 'text': 'fa fa-file-picture-o', 'selected': 'N'},
            {'id': 'fa fa-file-image-o', 'text': 'fa fa-file-image-o', 'selected': 'N'},
            {'id': 'fa fa-file-zip-o', 'text': 'fa fa-file-zip-o', 'selected': 'N'},
            {'id': 'fa fa-file-archive-o', 'text': 'fa fa-file-archive-o', 'selected': 'N'},
            {'id': 'fa fa-file-sound-o', 'text': 'fa fa-file-sound-o', 'selected': 'N'},
            {'id': 'fa fa-file-audio-o', 'text': 'fa fa-file-audio-o', 'selected': 'N'},
            {'id': 'fa fa-file-movie-o', 'text': 'fa fa-file-movie-o', 'selected': 'N'},
            {'id': 'fa fa-file-video-o', 'text': 'fa fa-file-video-o', 'selected': 'N'},
            {'id': 'fa fa-file-code-o', 'text': 'fa fa-file-code-o', 'selected': 'N'},
            {'id': 'fa fa-vine', 'text': 'fa fa-vine', 'selected': 'N'},
            {'id': 'fa fa-codepen', 'text': 'fa fa-codepen', 'selected': 'N'},
            {'id': 'fa fa-jsfiddle', 'text': 'fa fa-jsfiddle', 'selected': 'N'},
            {'id': 'fa fa-life-bouy', 'text': 'fa fa-life-bouy', 'selected': 'N'},
            {'id': 'fa fa-life-buoy', 'text': 'fa fa-life-buoy', 'selected': 'N'},
            {'id': 'fa fa-life-saver', 'text': 'fa fa-life-saver', 'selected': 'N'},
            {'id': 'fa fa-support', 'text': 'fa fa-support', 'selected': 'N'},
            {'id': 'fa fa-life-ring', 'text': 'fa fa-life-ring', 'selected': 'N'},
            {'id': 'fa fa-circle-o-notch', 'text': 'fa fa-circle-o-notch', 'selected': 'N'},
            {'id': 'fa fa-ra', 'text': 'fa fa-ra', 'selected': 'N'},
            {'id': 'fa fa-rebel', 'text': 'fa fa-rebel', 'selected': 'N'},
            {'id': 'fa fa-ge', 'text': 'fa fa-ge', 'selected': 'N'},
            {'id': 'fa fa-empire', 'text': 'fa fa-empire', 'selected': 'N'},
            {'id': 'fa fa-git-square', 'text': 'fa fa-git-square', 'selected': 'N'},
            {'id': 'fa fa-git', 'text': 'fa fa-git', 'selected': 'N'},
            {'id': 'fa fa-hacker-news', 'text': 'fa fa-hacker-news', 'selected': 'N'},
            {'id': 'fa fa-tencent-weibo', 'text': 'fa fa-tencent-weibo', 'selected': 'N'},
            {'id': 'fa fa-qq', 'text': 'fa fa-qq', 'selected': 'N'},
            {'id': 'fa fa-wechat', 'text': 'fa fa-wechat', 'selected': 'N'},
            {'id': 'fa fa-weixin', 'text': 'fa fa-weixin', 'selected': 'N'},
            {'id': 'fa fa-send', 'text': 'fa fa-send', 'selected': 'N'},
            {'id': 'fa fa-paper-plane', 'text': 'fa fa-paper-plane', 'selected': 'N'},
            {'id': 'fa fa-send-o', 'text': 'fa fa-send-o', 'selected': 'N'},
            {'id': 'fa fa-paper-plane-o', 'text': 'fa fa-paper-plane-o', 'selected': 'N'},
            {'id': 'fa fa-history', 'text': 'fa fa-history', 'selected': 'N'},
            {'id': 'fa fa-genderless', 'text': 'fa fa-genderless', 'selected': 'N'},
            {'id': 'fa fa-circle-thin', 'text': 'fa fa-circle-thin', 'selected': 'N'},
            {'id': 'fa fa-header', 'text': 'fa fa-header', 'selected': 'N'},
            {'id': 'fa fa-paragraph', 'text': 'fa fa-paragraph', 'selected': 'N'},
            {'id': 'fa fa-sliders', 'text': 'fa fa-sliders', 'selected': 'N'},
            {'id': 'fa fa-share-alt', 'text': 'fa fa-share-alt', 'selected': 'N'},
            {'id': 'fa fa-share-alt-square', 'text': 'fa fa-share-alt-square', 'selected': 'N'},
            {'id': 'fa fa-bomb', 'text': 'fa fa-bomb', 'selected': 'N'},
            {'id': 'fa fa-soccer-ball-o', 'text': 'fa fa-soccer-ball-o', 'selected': 'N'},
            {'id': 'fa fa-futbol-o', 'text': 'fa fa-futbol-o', 'selected': 'N'},
            {'id': 'fa fa-tty', 'text': 'fa fa-tty', 'selected': 'N'},
            {'id': 'fa fa-binoculars', 'text': 'fa fa-binoculars', 'selected': 'N'},
            {'id': 'fa fa-plug', 'text': 'fa fa-plug', 'selected': 'N'},
            {'id': 'fa fa-slideshare', 'text': 'fa fa-slideshare', 'selected': 'N'},
            {'id': 'fa fa-twitch', 'text': 'fa fa-twitch', 'selected': 'N'},
            {'id': 'fa fa-yelp', 'text': 'fa fa-yelp', 'selected': 'N'},
            {'id': 'fa fa-newspaper-o', 'text': 'fa fa-newspaper-o', 'selected': 'N'},
            {'id': 'fa fa-wifi', 'text': 'fa fa-wifi', 'selected': 'N'},
            {'id': 'fa fa-calculator', 'text': 'fa fa-calculator', 'selected': 'N'},
            {'id': 'fa fa-paypal', 'text': 'fa fa-paypal', 'selected': 'N'},
            {'id': 'fa fa-google-wallet', 'text': 'fa fa-google-wallet', 'selected': 'N'},
            {'id': 'fa fa-cc-visa', 'text': 'fa fa-cc-visa', 'selected': 'N'},
            {'id': 'fa fa-cc-mastercard', 'text': 'fa fa-cc-mastercard', 'selected': 'N'},
            {'id': 'fa fa-cc-discover', 'text': 'fa fa-cc-discover', 'selected': 'N'},
            {'id': 'fa fa-cc-amex', 'text': 'fa fa-cc-amex', 'selected': 'N'},
            {'id': 'fa fa-cc-paypal', 'text': 'fa fa-cc-paypal', 'selected': 'N'},
            {'id': 'fa fa-cc-stripe', 'text': 'fa fa-cc-stripe', 'selected': 'N'},
            {'id': 'fa fa-bell-slash', 'text': 'fa fa-bell-slash', 'selected': 'N'},
            {'id': 'fa fa-bell-slash-o', 'text': 'fa fa-bell-slash-o', 'selected': 'N'},
            {'id': 'fa fa-trash', 'text': 'fa fa-trash', 'selected': 'N'},
            {'id': 'fa fa-copyright', 'text': 'fa fa-copyright', 'selected': 'N'},
            {'id': 'fa fa-at', 'text': 'fa fa-at', 'selected': 'N'},
            {'id': 'fa fa-eyedropper', 'text': 'fa fa-eyedropper', 'selected': 'N'},
            {'id': 'fa fa-paint-brush', 'text': 'fa fa-paint-brush', 'selected': 'N'},
            {'id': 'fa fa-birthday-cake', 'text': 'fa fa-birthday-cake', 'selected': 'N'},
            {'id': 'fa fa-area-chart', 'text': 'fa fa-area-chart', 'selected': 'N'},
            {'id': 'fa fa-pie-chart', 'text': 'fa fa-pie-chart', 'selected': 'N'},
            {'id': 'fa fa-line-chart', 'text': 'fa fa-line-chart', 'selected': 'N'},
            {'id': 'fa fa-lastfm', 'text': 'fa fa-lastfm', 'selected': 'N'},
            {'id': 'fa fa-lastfm-square', 'text': 'fa fa-lastfm-square', 'selected': 'N'},
            {'id': 'fa fa-toggle-off', 'text': 'fa fa-toggle-off', 'selected': 'N'},
            {'id': 'fa fa-toggle-on', 'text': 'fa fa-toggle-on', 'selected': 'N'},
            {'id': 'fa fa-bicycle', 'text': 'fa fa-bicycle', 'selected': 'N'},
            {'id': 'fa fa-bus', 'text': 'fa fa-bus', 'selected': 'N'},
            {'id': 'fa fa-ioxhost', 'text': 'fa fa-ioxhost', 'selected': 'N'},
            {'id': 'fa fa-angellist', 'text': 'fa fa-angellist', 'selected': 'N'},
            {'id': 'fa fa-cc', 'text': 'fa fa-cc', 'selected': 'N'},
            {'id': 'fa fa-shekel', 'text': 'fa fa-shekel', 'selected': 'N'},
            {'id': 'fa fa-sheqel', 'text': 'fa fa-sheqel', 'selected': 'N'},
            {'id': 'fa fa-ils', 'text': 'fa fa-ils', 'selected': 'N'},
            {'id': 'fa fa-meanpath', 'text': 'fa fa-meanpath', 'selected': 'N'},
            {'id': 'fa fa-buysellads', 'text': 'fa fa-buysellads', 'selected': 'N'},
            {'id': 'fa fa-connectdevelop', 'text': 'fa fa-connectdevelop', 'selected': 'N'},
            {'id': 'fa fa-dashcube', 'text': 'fa fa-dashcube', 'selected': 'N'},
            {'id': 'fa fa-forumbee', 'text': 'fa fa-forumbee', 'selected': 'N'},
            {'id': 'fa fa-leanpub', 'text': 'fa fa-leanpub', 'selected': 'N'},
            {'id': 'fa fa-sellsy', 'text': 'fa fa-sellsy', 'selected': 'N'},
            {'id': 'fa fa-shirtsinbulk', 'text': 'fa fa-shirtsinbulk', 'selected': 'N'},
            {'id': 'fa fa-simplybuilt', 'text': 'fa fa-simplybuilt', 'selected': 'N'},
            {'id': 'fa fa-skyatlas', 'text': 'fa fa-skyatlas', 'selected': 'N'},
            {'id': 'fa fa-cart-plus', 'text': 'fa fa-cart-plus', 'selected': 'N'},
            {'id': 'fa fa-cart-arrow-down', 'text': 'fa fa-cart-arrow-down', 'selected': 'N'},
            {'id': 'fa fa-diamond', 'text': 'fa fa-diamond', 'selected': 'N'},
            {'id': 'fa fa-ship', 'text': 'fa fa-ship', 'selected': 'N'},
            {'id': 'fa fa-user-secret', 'text': 'fa fa-user-secret', 'selected': 'N'},
            {'id': 'fa fa-motorcycle', 'text': 'fa fa-motorcycle', 'selected': 'N'},
            {'id': 'fa fa-street-view', 'text': 'fa fa-street-view', 'selected': 'N'},
            {'id': 'fa fa-heartbeat', 'text': 'fa fa-heartbeat', 'selected': 'N'},
            {'id': 'fa fa-venus', 'text': 'fa fa-venus', 'selected': 'N'},
            {'id': 'fa fa-mars', 'text': 'fa fa-mars', 'selected': 'N'},
            {'id': 'fa fa-mercury', 'text': 'fa fa-mercury', 'selected': 'N'},
            {'id': 'fa fa-transgender', 'text': 'fa fa-transgender', 'selected': 'N'},
            {'id': 'fa fa-transgender-alt', 'text': 'fa fa-transgender-alt', 'selected': 'N'},
            {'id': 'fa fa-venus-double', 'text': 'fa fa-venus-double', 'selected': 'N'},
            {'id': 'fa fa-mars-double', 'text': 'fa fa-mars-double', 'selected': 'N'},
            {'id': 'fa fa-venus-mars', 'text': 'fa fa-venus-mars', 'selected': 'N'},
            {'id': 'fa fa-mars-stroke', 'text': 'fa fa-mars-stroke', 'selected': 'N'},
            {'id': 'fa fa-mars-stroke-v', 'text': 'fa fa-mars-stroke-v', 'selected': 'N'},
            {'id': 'fa fa-mars-stroke-h', 'text': 'fa fa-mars-stroke-h', 'selected': 'N'},
            {'id': 'fa fa-neuter', 'text': 'fa fa-neuter', 'selected': 'N'},
            {'id': 'fa fa-facebook-official', 'text': 'fa fa-facebook-official', 'selected': 'N'},
            {'id': 'fa fa-pinterest-p', 'text': 'fa fa-pinterest-p', 'selected': 'N'},
            {'id': 'fa fa-whatsapp', 'text': 'fa fa-whatsapp', 'selected': 'N'},
            {'id': 'fa fa-server', 'text': 'fa fa-server', 'selected': 'N'},
            {'id': 'fa fa-user-plus', 'text': 'fa fa-user-plus', 'selected': 'N'},
            {'id': 'fa fa-user-times', 'text': 'fa fa-user-times', 'selected': 'N'},
            {'id': 'fa fa-hotel', 'text': 'fa fa-hotel', 'selected': 'N'},
            {'id': 'fa fa-bed', 'text': 'fa fa-bed', 'selected': 'N'},
            {'id': 'fa fa-viacoin', 'text': 'fa fa-viacoin', 'selected': 'N'},
            {'id': 'fa fa-train', 'text': 'fa fa-train', 'selected': 'N'},
            {'id': 'fa fa-subway', 'text': 'fa fa-subway', 'selected': 'N'},
            {'id': 'fa fa-medium', 'text': 'fa fa-medium', 'selected': 'N'}
        ];

        return ({
            getOkButtonClass: getOkButtonClass,
            setOkButtonClass: setOkButtonClass,
            getCancelButtonClass: getCancelButtonClass,
            setCancelButtonClass: setCancelButtonClass,
            openSelectionDialog: openSelectionDialog
        });

        function getOkButtonClass() {
            return okButtonClass;
        }

        function setOkButtonClass(newOkButtonClass) {
            okButtonClass = newOkButtonClass;
        }

        function getCancelButtonClass() {
            return cancelButtonClass;
        }

        function setCancelButtonClass(newCancelButtonClass) {
            cancelButtonClass = newCancelButtonClass;
        }

        function setWindowClass(newWindowClass) {
            windowClass = newWindowClass;
        }

        function openSelectionDialog(title, variable, selectionType, windowClass, callback) {
            return ModalSelectionWindowService.openSelectionDialog(title, variable, data, selectionType, windowClass, callback);
        }
    }


})();