server:
  port: 9000

security:
  sessions: NEVER

platform:
  core:
    modules:
      # Add here your module serviceId
      registeredServices:
        -
          serviceId: abixen-platform-business-intelligence-service
        -
          serviceId: abixen-platform-web-content-module


---


spring:
  profiles: cloud
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbit-mq
    port: 5672
    username: guest
    password: guest
platform:
  core:
    jdbc:
      driverClassName: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
      databaseUrl: jdbc:postgresql://core-postgres-database:5432/abixen_platform_core
      username: abixen
      password: fy2Lkxw201sV
    mail:
      outgoing:
        host: abixen.home.pl
        port: 587
        user:
          username: test@abixen.com
          name: Abixen Platform
          password: 6!h9Cp2Uv^M2Xz79r
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    resource:
      imageLibraryDirectory: /data/image-library
      themesDirectory: /data/themes
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
platform:
  core:
    jdbc:
      driverClassName: org.h2.Driver
      dialect: org.hibernate.dialect.H2Dialect
      databaseUrl: jdbc:h2:file:~/abixen-platform-h2-db
      username: sa
      password:
    mail:
      outgoing:
        host: abixen.home.pl
        port: 587
        user:
          username: test@abixen.com
          name: Abixen Platform
          password: 6!h9Cp2Uv^M2Xz79r
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    resource:
      imageLibraryDirectory: ${baseDir}/../data/image-library
      themesDirectory: ${baseDir}/../data/themes

eureka:
  instance:
    hostname: localhost
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/