server:
  port: 9090



---


spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  zipkin:
    baseUrl: http://zipkin:9411

  cloud:
    gateway:
      routes:
      # Begin of custom module microservices - add mapping relevant to your microservice

      # Begin of Business Intelligence microservice
      - id: businessIntelligenceApplication
        uri: http://business-intelligence-service:9091/service/abixen/business-intelligence/application
        predicates:
        - Path=/service/abixen/business-intelligence/application/**
      - id: businessIntelligenceApplicationApi
        uri: http://business-intelligence-service:9091/api/service/abixen/business-intelligence/application
        predicates:
        - Path=/api/service/abixen/business-intelligence/application/**
      - id: businessIntelligenceAdmin
        uri: http://business-intelligence-service:9091/service/abixen/business-intelligence/control-panel
        predicates:
        - Path=/service/abixen/business-intelligence/control-panel/**
      - id: businessIntelligenceAdminApi
        uri: http://business-intelligence-service:9091/api/service/abixen/business-intelligence/control-panel
        predicates:
        - Path=/api/service/abixen/business-intelligence/control-panel/**
      # End of Business Intelligence microservice

      # Begin of Web Content microservice
      - id: webContentApplication
        uri: http://web-content-service:9092/service/abixen/web-content/application
        predicates:
        - Path=/service/abixen/web-content/application/**
      - id: webContentApplicationApi
        uri: http://web-content-service:9092/api/service/abixen/web-content/application
        predicates:
        - Path=/api/service/abixen/web-content/application/**
      - id: webContentAdmin
        uri: http://web-content-service:9092/service/abixen/web-content/control-panel
        predicates:
        - Path=/service/abixen/web-content/control-panel/**
      - id: webContentAdminApi
        uri: http://web-content-service:9092/api/service/abixen/web-content/control-panel
        predicates:
        - Path=/api/service/abixen/web-content/control-panel/**
      # End of Web Content microservice

      # End of custom module microservices
      - id: api
        uri: http://core:9000/api
        predicates:
        - Path=/api/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
  zipkin:
    baseUrl: http://localhost:9411

  cloud:
    gateway:
      routes:
      # Begin of custom module microservices - add mapping relevant to your microservice

      # Begin of Business Intelligence microservice
      - id: businessIntelligenceApplication
        uri: http://localhost:9091/service/abixen/business-intelligence/application
        predicates:
        - Path=/service/abixen/business-intelligence/application/**
      - id: businessIntelligenceApplicationApi
        uri: http://localhost:9091/api/service/abixen/business-intelligence/application
        predicates:
        - Path=/api/service/abixen/business-intelligence/application/**
      - id: businessIntelligenceAdmin
        uri: http://localhost:9091/service/abixen/business-intelligence/control-panel
        predicates:
        - Path=/service/abixen/business-intelligence/control-panel/**
      - id: businessIntelligenceAdminApi
        uri: http://localhost:9091/api/service/abixen/business-intelligence/control-panel
        predicates:
        - Path=/api/service/abixen/business-intelligence/control-panel/**
      # End of Business Intelligence microservice

      # Begin of Web Content microservice
      - id: webContentApplication
        uri: http://localhost:9092/service/abixen/web-content/application
        predicates:
        - Path=/service/abixen/web-content/application/**
      - id: webContentApplicationApi
        uri: http://localhost:9092/api/service/abixen/web-content/application
        predicates:
        - Path=/api/service/abixen/web-content/application/**
      - id: webContentAdmin
        uri: http://localhost:9092/service/abixen/web-content/control-panel
        predicates:
        - Path=/service/abixen/web-content/control-panel/**
      - id: webContentAdminApi
        uri: http://localhost:9092/api/service/abixen/web-content/control-panel
        predicates:
        - Path=/api/service/abixen/web-content/control-panel/**
      # End of Web Content microservice

      # End of custom module microservices
      - id: api
        uri: http://localhost:9000/api
        predicates:
        - Path=/api/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
eureka:
  instance:
    hostname: localhost
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
