server:
  port: 9090

security:
  sessions: ALWAYS


---


spring:
  profiles: cloud
  redis:
    host: redis
    port: 6379

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    resource:
      path: /resource/**
      url: http://core:9000
      sensitive-headers:
    api:
      path: /api/**
      url: http://core:9000/api
      sensitive-headers:

    # Begin of custom module microservices - add mapping relevant to your microservice

    # Begin of businessintelligence microservice
    businessintelligenceApplication:
      path: /application/businessintelligence/abixen/**
      url: http://localhost:9091/application/businessintelligence/abixen
      sensitive-headers:
    businessintelligenceAdmin:
      path: /admin/businessintelligence/abixen/**
      url: http://localhost:9091/admin/businessintelligence/abixen
      sensitive-headers:
    # End of businessintelligence microservice

    # End of custom module microservices

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
    api:
      path: /api/**
      url: http://localhost:9000/api
      sensitive-headers:
    businessintelligenceApplication:
      path: /application/businessintelligence/abixen/**
      url: http://localhost:9091/application/businessintelligence/abixen
      sensitive-headers:
    businessintelligenceAdmin:
      path: /admin/businessintelligence/abixen/**
      url: http://localhost:9091/admin/businessintelligence/abixen
      sensitive-headers:

eureka:
  instance:
    hostname: localhost
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/