server:
  port: 8080

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api:
      path: /api/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/api
      sensitive-headers:
    user:
      path: /user
      url: http://${abixen.services.gateway.uri:localhost}:9090/
      sensitive-headers:

    # Begin of custom module microservices - add mapping relevant to your microservice

    # Begin of Business Intelligence microservice
    businessIntelligenceApplication:
      path: /service/abixen/business-intelligence/application/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/service/abixen/business-intelligence/application
      sensitive-headers:
    businessIntelligenceApplicationApi:
      path: /api/service/abixen/business-intelligence/application/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/api/service/abixen/business-intelligence/application
      sensitive-headers:
    businessIntelligenceAdmin:
      path: /service/abixen/business-intelligence/admin/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/service/abixen/business-intelligence/admin/
      sensitive-headers:
    businessIntelligenceAdminApi:
      path: /api/service/abixen/business-intelligence/admin/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/api/service/abixen/business-intelligence/admin/
      sensitive-headers:
    # End of Business Intelligence microservice

    # Begin of Web Content microservice
    webContentApplication:
      path: /service/abixen/web-content/application/**
      url: http://${abixen.services.gateway.uri:localhost}:9092/service/abixen/web-content/application/
      sensitive-headers:
    webContentApplicationApi:
      path: /api/service/abixen/web-content/application/**
      url: http://${abixen.services.gateway.uri:localhost}:9092/api/service/abixen/web-content/application/
      sensitive-headers:
    webContentAdmin:
      path: /service/abixen/web-content/admin/**
      url: http://${abixen.services.gateway.uri:localhost}:9092/service/abixen/web-content/admin/
      sensitive-headers:
    webContentAdminApi:
      path: /api/service/abixen/web-content/admin/**
      url: http://${abixen.services.gateway.uri:localhost}:9092/api/service/abixen/web-content/admin/
      sensitive-headers:
    # End of Web Content microservice

    # End of custom module microservices

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


---


spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkin:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  zipkin:
    baseUrl: http://localhost:9411

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
