server:
  port: 8080

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api:
      path: /api/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/api
      sensitive-headers:
    user:
      path: /user
      url: http://${abixen.services.gateway.uri:localhost}:9090/
      sensitive-headers:

    # Begin of custom module microservices - add mapping relevant to your microservice

    # Begin of modules microservice
    modulesApplication:
      path: /application/modules/abixen/**
      serviceId: http://${abixen.services.gateway.uri:localhost}:9090/application/modules/abixen
      sensitive-headers:
    modulesAdmin:
      path: /admin/modules/abixen/**
      url: http://${abixen.services.gateway.uri:localhost}:9090/admin/modules/abixen
      sensitive-headers:
    # End of modules microservice

    # End of custom module microservices

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


---


spring:
  profiles: cloud

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/