server:
  port: ${vcap.application.port:9000}

---

spring:
  profiles: cloud
platform:
  core:
    jdbc:
      driverClassName: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
      databaseUrl: jdbc:postgresql://localhost:5432/abixen_platform
      username: postgres
      password: postgres
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN:localhost}
    nonSecurePort: 9000
    metadataMap:
      cluster: AbixenPlatform
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---

spring:
  profiles: dev
platform:
  core:
    jdbc:
      driverClassName: org.h2.Driver
      dialect: org.hibernate.dialect.H2Dialect
      databaseUrl: jdbc:h2:file:~/abixen-platform-h2-db
      username: sa
      password:
    mail:
      outgoing:
        host: abixen.home.pl
        port: 587
        user:
          username: test@abixen.com
          name: Abixen Platform
          password: 6!h9Cp2Uv^M2Xz79r
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    resource:
      imageLibraryDirectory: F:/abixen-platform/data/image-library/
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN:localhost}
    nonSecurePort: 9000
    metadataMap:
      cluster: AbixenPlatform
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---

spring:
  profiles: test
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN:localhost}
    nonSecurePort: 9000
    metadataMap:
      cluster: AbixenPlatform
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
platform:
  core:
    jdbc:
      #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #dialect: org.hibernate.dialect.H2Dialect
      #databaseUrl: jdbc:log4jdbc:h2:file:~/h2-db
      #username: sa
      #password: postgres
      driverClassName: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
      databaseUrl: jdbc:postgresql://localhost:5432/abixen_platform
      username: postgres
      password: postgres
    mail:
      outgoing:
        host: abixen.home.pl
        port: 587
        user:
          username: test@abixen.com
          name: Abixen Platform
          password: 6!h9Cp2Uv^M2Xz79r
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    resource:
      imageLibraryDirectory: F:/abixen-platform/data/image-library/