server:
  port: 9090

security:
  sessions: ALWAYS


---


spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  zipkin:
    baseUrl: http://zipkin:9411

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    # Begin of custom module microservices - add mapping relevant to your microservice

    # Begin of Business Intelligence microservice
    businessIntelligenceApplication:
      path: /service/abixen/business-intelligence/application/**
      url: http://business-intelligence-service:9091/service/abixen/business-intelligence/application
      sensitive-headers:
    businessIntelligenceApplicationApi:
      path: /api/service/abixen/business-intelligence/application/**
      url: http://business-intelligence-service:9091/api/service/abixen/business-intelligence/application
      sensitive-headers:
    businessIntelligenceAdmin:
      path: /service/abixen/business-intelligence/control-panel/**
      url: http://business-intelligence-service:9091/service/abixen/business-intelligence/control-panel
      sensitive-headers:
    businessIntelligenceAdminApi:
      path: /api/service/abixen/business-intelligence/control-panel/**
      url: http://business-intelligence-service:9091/api/service/abixen/business-intelligence/control-panel
      sensitive-headers:
    # End of Business Intelligence microservice

    # Begin of Web Content microservice
    webContentApplication:
      path: /service/abixen/web-content/application/**
      url: http://web-content-service:9092/service/abixen/web-content/application
      sensitive-headers:
    webContentApplicationApi:
      path: /api/service/abixen/web-content/application/**
      url: http://web-content-service:9092/api/service/abixen/web-content/application
      sensitive-headers:
    webContentAdmin:
      path: /service/abixen/web-content/control-panel/**
      url: http://web-content-service:9092/service/abixen/web-content/control-panel
      sensitive-headers:
    webContentAdminApi:
      path: /api/service/abixen/web-content/control-panel/**
      url: http://web-content-service:9092/api/service/abixen/web-content/control-panel
      sensitive-headers:
    # End of Web Content microservice

    # End of custom module microservices
    resource:
      path: /resource/**
      url: http://core:9000
      sensitive-headers:
    api:
      path: /api/**
      url: http://core:9000/api
      sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
  zipkin:
    baseUrl: http://localhost:9411

zuul:
  routes:
    # Begin of custom module microservices - add mapping relevant to your microservice

    # Begin of Business Intelligence microservice
    businessIntelligenceApplication:
      path: /service/abixen/business-intelligence/application/**
      url: http://localhost:9091/service/abixen/business-intelligence/application
      sensitive-headers:
    businessIntelligenceApplicationApi:
      path: /api/service/abixen/business-intelligence/application/**
      url: http://localhost:9091/api/service/abixen/business-intelligence/application
      sensitive-headers:
    businessIntelligenceAdmin:
      path: /service/abixen/business-intelligence/control-panel/**
      url: http://localhost:9091/service/abixen/business-intelligence/control-panel
      sensitive-headers:
    businessIntelligenceAdminApi:
      path: /api/service/abixen/business-intelligence/control-panel/**
      url: http://localhost:9091/api/service/abixen/business-intelligence/control-panel
      sensitive-headers:
    # End of Business Intelligence microservice

    # Begin of Web Content microservice
    webContentApplication:
      path: /service/abixen/web-content/application/**
      url: http://localhost:9092/service/abixen/web-content/application
      sensitive-headers:
    webContentApplicationApi:
      path: /api/service/abixen/web-content/application/**
      url: http://localhost:9092/api/service/abixen/web-content/application
      sensitive-headers:
    webContentAdmin:
      path: /service/abixen/web-content/control-panel/**
      url: http://localhost:9092/service/abixen/web-content/control-panel/
      sensitive-headers:
    webContentAdminApi:
      path: /api/service/abixen/web-content/control-panel/**
      url: http://localhost:9092/api/service/abixen/web-content/control-panel/
      sensitive-headers:
    # End of Web Content microservice

    # End of custom module microservices
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
    api:
      path: /api/**
      url: http://localhost:9000/api
      sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
eureka:
  instance:
    hostname: localhost
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
