server:
  port: 9000

security:
  sessions: NEVER


---


spring:
  profiles: cloud
  redis:
    host: redis
    port: 6379
platform:
  core:
    jdbc:
      driverClassName: org.h2.Driver
      dialect: org.hibernate.dialect.H2Dialect
      databaseUrl: jdbc:h2:file:~/abixen-platform-h2-db
      username: sa
      password:
    mail:
      outgoing:
        host: abixen.home.pl
        port: 587
        user:
          username: test@abixen.com
          name: Abixen Platform
          password: 6!h9Cp2Uv^M2Xz79r
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    resource:
      imageLibraryDirectory: /data/db
eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${abixen.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
platform:
  core:
    jdbc:
      driverClassName: org.h2.Driver
      dialect: org.hibernate.dialect.H2Dialect
      databaseUrl: jdbc:h2:file:~/abixen-platform-h2-db
      username: sa
      password:
    mail:
      outgoing:
        host: abixen.home.pl
        port: 587
        user:
          username: test@abixen.com
          name: Abixen Platform
          password: 6!h9Cp2Uv^M2Xz79r
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    resource:
      imageLibraryDirectory: ${baseDir}/../data/image-library

eureka:
  instance:
    hostname: localhost
    metadataMap:
      cluster: AbixenPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/